services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=github_trending
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
    - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=github_trending
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile.spa
    ports:
      - "5173:5173"
    depends_on:
      - api
volumes:
  pgdata:
